TOP_CHORD_LOWER_BOUND = 20
TOP_CHORD_UPPER_BOUND = 300
BOTTOM_CHORD_LOWER_BOUND = 20
BOTTOM_CHORD_UPPER_BOUND = 300
POST_LOWER_BOUND = 20
POST_UPPER_BOUND = 300
DIAGONAL_LOWER_BOUND = 20
DIAGONAL_UPPER_BOUND = 300

DEFAULT_LENGTH = 20.0
DEFAULT_SEGMENTS = 5
DEFAULT_MIN_STRENGTH = 3000.0
DEFAULT_POPULATION_SIZE = 150
DEFAULT_GENERATIONS = 50
DEFAULT_MUTATION_RATE = 0.1
DEFAULT_PROCESSES = 1

DEFAULT_TOP_CHORD_DIAMETER = 150
DEFAULT_BOTTOM_CHORD_DIAMETER = 200
DEFAULT_POSTS_DIAMETER = 100
DEFAULT_DIAGONALS_DIAMETER = 75
STEEL_DENSITY = 7850
