# mm
TOP_CHORD_LOWER_BOUND = 20 
TOP_CHORD_UPPER_BOUND = 300
BOTTOM_CHORD_LOWER_BOUND = 20
BOTTOM_CHORD_UPPER_BOUND = 300
POST_LOWER_BOUND = 20
POST_UPPER_BOUND = 300
DIAGONAL_LOWER_BOUND = 20
DIAGONAL_UPPER_BOUND = 300

# mm
DEFAULT_TOP_CHORD_DIAMETER = 150
DEFAULT_BOTTOM_CHORD_DIAMETER = 200
DEFAULT_POST_DIAMETER = 100
DEFAULT_DIAGONAL_DIAMETER = 75

BRIDGE_HEIGHT = 5 # m

DEFAULT_LENGTH = 20.0 # m
DEFAULT_SEGMENTS = 5
DEFAULT_MIN_STRENGTH = 3000.0 # kg
DEFAULT_POPULATION_SIZE = 150
DEFAULT_GENERATIONS = 50
DEFAULT_MUTATION_RATE = 0.1
DEFAULT_PROCESSES = 1

STEEL_DENSITY = 7850 # kg/m3
YOUNGS_MODULUS = 210e9 # Pa
ELASTIC_LIMIT_OF_STEEL = 355e6 # Pa
KG_TO_NEWTON = 10
MM_TO_M = 1e-3

PROBLEM_DIMENSION = 2
NODES_PER_ELEMENT = 2
ELEMENTS_PER_SEGMENT = 4
NODES_PER_SEGMENT = 2